cat("Podpunkt 1\n")
print(dpois(x=5, lambda=6))
cat("\nPodpunkt 2\n")
print(ppois(q=3, lambda=6, lower.tail=FALSE))
cat("\nPodpunkt 3\n")
print(ppois(q=5, lambda=6)-ppois(q=2, lambda=6))
cat("\nPodpunkt 4\n")
ilosc_samochodow<-0:30
pstwo<-dpois(x=ilosc_samochodow, lambda = 6)
plot(x=ilosc_samochodow, y=pstwo, type="h")