cat("Podpunkt 1\n")
print(punif(q=7, min=4, max=12))
cat("\nPodpunkt 2\n")
print(punif(q=11, min=4, max=12)-punif(q=5, min=4, max=12))
cat("\nPodpunkt 3\n")
print(punif(q=10, min=4, max=12, lower.tail=FALSE))
cat("\nPodpunkt 4\n")
print(qunif(p=0.6, mi=4, max=12, lower.tail=FALSE))