cat("Podpunkt 1\n")
print(pexp(q=0.5, rate=4, lower.tail=FALSE))
cat("\nPodpunkt 2\n")
print(pexp(q=1/3, rate=4))
cat("\nPodpunkt 3\n")
print(pexp(q=4/3, rate=4)-pexp(q=2/3, rate=4))
cat("\nPodpunkt 4\n")
print(qexp(p=0.2, rate=4, lower.tail = FALSE))
cat("\nPodpunkt 5\n")
czas<-seq(0.00, 3.00, 0.01)
pstwo<-dexp(x=czas, rate=4)
plot(x=czas, y=pstwo, type="l")